# Generated by Django 4.1.4 on 2022-12-12 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('category_name', models.CharField(blank=True, help_text='Kategori Adı', max_length=150, null=True)),
                ('category_code', models.CharField(blank=True, help_text='Kategori kodu', max_length=150, null=True, unique=True)),
                ('created_by', models.ForeignKey(help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('product_name', models.CharField(help_text='Ürün adı', max_length=250)),
                ('product_code', models.CharField(max_length=64, unique=True)),
                ('category', models.ManyToManyField(to='app.category')),
                ('created_by', models.ForeignKey(help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
